"""
afk_supervisor.drivers.base — 驱动器基类与抽象接口
==================================================
"""

from pathlib import Path
from typing import Optional, Protocol


class Driver(Protocol):
    session_id: Optional[str]
    jsonl: Optional[Path]
    proc: Optional[object]
    provider_name: str

    def launch(self, prompt_path: Path): ...
    def resume(self, prompt_path: Path): ...
    def fork(self, prompt_path: Path): ...
    def interrupt(self) -> bool: ...
    def wait_exit(self, timeout: float) -> bool: ...
    def kill_tree(self) -> None: ...
    def has_next(self) -> bool: ...
